struct ROLE_ITEM_SET{			
	char	BYTE_0;	//
	char	STRING_1[9];	//
	char	Item1_Flag;	//
	char	Item1_ID;	//
	char	Item1_Have;	//
	char	STRING_13[7];	//
	char	Item2_Flag;	//
	char	Item2_ID;	//
	char	Item2_Have;	//
	char	STRING_23[7];	//
	char	Item3_Flag;	//
	char	Item3_ID;	//
	char	Item3_Have;	//
	char	STRING_33[7];	//
	char	Item4_Flag;	//
	char	Item4_ID;	//
	char	Item4_Have;	//
	char	STRING_43[7];	//
	char	Item5_Flag;	//
	char	Item5_ID;	//
	char	Item5_Have;	//
	char	STRING_53[7];	//
	char	Item6_Flag;	//
	char	Item6_ID;	//
	char	Item6_Have;	//
	char	STRING_63[7];	//
	char	STRING_70[270];	//
	char	ItemBoxNum;	//
	char	STRING_341[347];	//
};			
